name: video_player_tizen
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Tizen.
version: 2.2.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h

dev_dependencies:
  pedantic: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  video_player_web: ^2.0.0
  html: ^0.15.0

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0<3.0.0"
